export interface Project {
    id: number;
    name: string;
    type: string,
    link: string | "#",
    site: string | "#",
    date: string,
    photos: string[] | null,
    tools: string[],
    description: string,
    role: string,
}

export const projects: Project[] = [
    {
        id: 1,
        name: "we get together",
        type: "web app",
        link: "https://github.com/cheetodustflori/We-Get-Together",
        site: "https://cs484-efkn.web.app",
        date: "december 2025",
        photos: ["/projects/wegettog.png"],
        tools: ["React, TailwindCSS, Firebase (Auth, Cloud Functions, Firestore, Hosting), Google Maps API (Distance Matrix, Places, Routes), Framer Motion, Browser Geolocation API, Biome.js, pre-commit"],
        description: "We Get Together is a tool for friends to find a common gathering place. Using session codes, users can join a shared session with real-time updates, share their unique locations, and calculate a midpoint where everyone can meet.",
        role: "Frontend Engineer",
    },
    {
        id: 2,
        name: "sweet t bakery",
        type: "web app",
        link: "some-url",
        site: "https://wics-uic.github.io/Sweet-T/",
        date: "aug 2025 - december 2025",
        photos: ["/projects/sweetT.png"],
        tools: ["Figma, Astro, TailwindCSS, MongoDB, Express, Node.js"],
        description: "We built a website prototype for a local bakery: Sweet T. We provided add-to-cart functionality, and an admin dashboard with a working backend for user authentication and order management.",
        role: "Dev Lead",
    },
    {
        id: 3,
        name: "commuter connect",
        type: "web app",
        link: "some-url",
        site: "",
        date: "spring 2025",
        photos: ["/projects/commuter-connect.gif"],
        tools: ["React (Router), Flask, Firebase, Google Routes + Places APIs"],
        description: `
        Commuter Connect is a web application built with React, Flask, Firebase, using data from Google Routes + Places API, designed to assist and connect commuter students at UIC (University of Illinois Chicago). At UIC, a large percentage of students are commuters who face long, sometimes lonely journeys to and from campus. Many lack a reliable network to coordinate rides, share routes, or connect with other commuters. 
        
        Commuter Connect solves this problem by offering a platform that helps commuters organize and optimize their daily routes, connects students with "commute buddies" for a more convenient and social travel experience, and builds community among students who might otherwise feel isolated due to commuting. 
        
        Our mission is to turn commuting into an opportunity for connection, convenience, and community.`,
        role: "Full Stack Developer",
    },
    {
        id: 4,
        name: "wics website",
        type: "web app",
        link: "https://github.com/wics-uic/WiCS-Website",
        site: "https://wics-uic.github.io/WiCS-Website/",
        date: "spring 2025",
        photos: ["/projects/wics-site.png"],
        tools: ["Figma, Astro, TailwindCSS"],
        description: "I led a cohort of 15 students to build the official Women in Computer Science (WICS) website. Features include an about, contact, and sponsorship page.",
        role: "Dev Lead",
    },
    {
        id: 5,
        name: "sparkhacks 2026",
        type: "web app",
        link: "https://github.com/SparkHacks/spark-web-2026", // https://github.com/SparkHacks/spark-dashboard
        site: "sparkhacks.org",
        date: "august 2025 - january 2026",
        photos: ["/projects/sh26.png"],
        tools: ["Figma, Astro, TailwindCSS"],
        description: "I led the development of the official SparkHacks website for UIC's annual Hackathon. Mobile responsive.",
        role: "Web Dev Lead",
    },
    {
        id: 6,
        name: "spackhacks 2025",
        type: "web app",
        link: "some-url",
        site: "https://web.archive.org/web/20250315201353/https://www.sparkhacks.org/",
        date: "august 2024 - january 2025",
        photos: ["/projects/sh25.png"],
        tools: ["Figma, Astro, TailwindCSS"],
        description: "I was part of the development of the official SparkHacks Website for UIC's annual Hackathon. Mobile responsive.",
        role: "Web Dev Member",
    },
    {
        id: 7,
        name: "Travel Bucket List",
        type: "mobile app",
        link: "https://github.com/cheetodustflori/Travel-Bucket-List",
        site: "",
        date: "spring 2024",
        photos: [""],
        tools: ["Swift, Xcode"],
        description: "One of my first CS projects! I taught a group of students how to use Swift and built a Travel Bucket List app that tracks travel destinations and categorizes them.",
        role: "SIG IOS Lead",
    },
    {
        id: 8,
        name: "personal site 2024",
        type: "web app",
        link: "some-url",
        site: "https://cheetodustflori.github.io/Personal-Website/",
        date: "summer 2024",
        photos: ["/projects/personal-site-2024.png"],
        tools: ["HTML, CSS, JS"],
        description: "My first personal website! This website displays some of my hobbies and CS projects.",
        role: "Developer",
    },
    {
        id: 9,
        name: "leaf project",
        type: "web app",
        link: "https://github.com/cheetodustflori/Leaf-Project-2024",
        site: "mobile app",
        date: "fall 2023",
        photos: ["/projects/leaf.png"],
        tools: ["Swift, Xcode"],
        description: "Financial literacy app that aims to educate its users through fun tasks. I built the entire frontend.",
        role: "iOS Developer",
    },
    {
        id: 10,
        name: "course bits",
        type: "web app",
        link: "https://github.com/cheetodustflori/CourseBits",
        site: "",
        date: "spring 2024",
        photos: ["/projects/courseplanner.png"],
        tools: ["Figma, React"],
        description: "WiCS Dev Project: Fall 2024. The first iteration fo the WiCS Dev Project. We built a course catalog of UIC courses with difficulty ratings and topics attached to each course.",
        role: "Dev Lead",
    },
    {
        id: 11,
        name: "sparkhacks dashboard",
        type: "web app",
        link: "https://github.com/SparkHacks/spark-web-2026", // https://github.com/SparkHacks/spark-dashboard
        site: "sparkhacks.org",
        date: "august 2024 - present",
        photos: ["/projects/sh26.png"],
        tools: ["Figma, Astro, TailwindCSS, Firebase, QRScanner"],
        description: "SparkHacks application manager. User authentication. Allows admin users to manage and view applications, as well as scan user QR codes and update their status. Allows applicants to submit and view their application status.",
        role: "",
    },
];