import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "./components/navbar";
import "./globals.css";
import { ViewTransition } from "react";


export const larken = localFont({
  src: [
    { path: "../public/fonts/Larken-Regular.otf", weight: "400", style: "normal" },
    { path: "../public/fonts/Larken-Bold.otf", weight: "700", style: "normal" },
    { path: "../public/fonts/Larken-Black.otf", weight: "900", style: "normal" },
    { path: "../public/fonts/Larken-Italic.otf", weight: "400", style: "italic" },
  ],
  variable: "--font-larken",
  display: "swap",
});

export const pecita = localFont({
  src: [
    { path: "../public/fonts/Pecita.otf", weight: "400", style: "normal" }
  ],
  variable: "--font-pecita",
  display: "swap",
});

const almarai = Almarai({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-almarai",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Flechori",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${almarai.variable} ${larken.variable} ${pecita.variable} antialiased`}
      >
        <ViewTransition>
        <div className=" flex flex-col gap-5 m-auto h-screen w-2xl p-[15px]">

        <NavBar/>
        {children}
        </div>
        </ViewTransition>
      </body>
    </html>
  );
}
