import type { Metadata } from "next";
import { Geist, Geist_Mono, Almarai } from "next/font/google";
import larken from "next/font/local";
import "./globals.css";

const flechori = larken({
  src: [
    {
      path: "../public/fonts/Larken-Black.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Larken-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-flechori",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const almarai = Geist({
  variable: "--font-almarai",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Flechori",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${almarai.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
